plot(density(results1))
plot(density(results2))
plot(density(results3, na.rm=TRUE))
plot(density(results4, na.rm=TRUE))
plot(density(results5, na.rm=TRUE))
plot(density(results6, na.rm=TRUE))
plot(density(results7))
plot(density(results8))
plot(density(results9, na.rm=TRUE))
plot(density(results10, na.rm=TRUE))
plot(density(results11, na.rm=TRUE))
plot(density(results12, na.rm=TRUE))
plot(density(results13))
plot(density(results14))
plot(density(results15))
plot(density(results16))
plot(density(results17))
plot(density(results18))
plot(density(results19))
plot(density(results20))
plot(density(results21))
plot(density(results22))
plot(density(results23))
plot(density(results24))
plot(density(results25))
plot(density(results26))
plot(density(results27))
plot(density(results28))
plot(density(results29))
plot(density(results30))
plot(density(results31))
plot(density(results32))
plot(density(results33))
plot(density(results34))
plot(density(results35))
plot(density(results36))
plot(density(results37))
plot(density(results38))
plot(density(results39))
plot(density(results40, na.rm=TRUE))
plot(density(results41))
plot(density(results42))
plot(density(results43))
plot(density(results44))
plot(density(results45))
plot(density(results46, na.rm=TRUE))
plot(density(results47))
plot(density(results48))
