wilcox.test(results1,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results2,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results3,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results4,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results5,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results6,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results7,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results8,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results9,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results10,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results11,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results12,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results13,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results14,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results15,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results16,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results17,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results18,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results19,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results20,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results21,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results22,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results23,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results24,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results25,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results26,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results27,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results28,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results29,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results30,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results31,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results32,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results33,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results34,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results35,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results36,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results37,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results38,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results39,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results40,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results41,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results42,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results43,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results44,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results45,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results46,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999, na.rm=TRUE)
wilcox.test(results47,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
wilcox.test(results48,alternative="two.sided",correct=TRUE,conf.int=TRUE,conf.level=0.999)
